// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;
using PharmaceuticalWarehousing;

#nullable disable

namespace PharmaceuticalWarehousing.Migrations
{
    [DbContext(typeof(PharmaceuticalWarehousingDbContext))]
    [Migration("20221221153143_newTable8")]
    partial class newTable8
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "7.0.1")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("PharmaceuticalWarehousing.Models.Category", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.ToTable("Category");
                });

            modelBuilder.Entity("PharmaceuticalWarehousing.Models.Check", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<int?>("InvoiceId")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("InvoiceId");

                    b.ToTable("Check");
                });

            modelBuilder.Entity("PharmaceuticalWarehousing.Models.Counterparty", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("Flat")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("House")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int>("ITN")
                        .HasColumnType("integer");

                    b.Property<string>("Phone")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Street")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.ToTable("Counterparty");
                });

            modelBuilder.Entity("PharmaceuticalWarehousing.Models.Invoice", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<double>("AmountPayable")
                        .HasColumnType("double precision");

                    b.Property<int?>("BuyerId")
                        .HasColumnType("integer");

                    b.Property<DateTime>("DateOfDischarge")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int?>("SalesmanId")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("BuyerId");

                    b.HasIndex("SalesmanId");

                    b.ToTable("Invoice");
                });

            modelBuilder.Entity("PharmaceuticalWarehousing.Models.Manufacturer", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.ToTable("Manufacturer");
                });

            modelBuilder.Entity("PharmaceuticalWarehousing.Models.Medication", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("BestBeforeDate")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int?>("CheckId")
                        .HasColumnType("integer");

                    b.Property<DateTime>("DateOfManufacture")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int?>("ManufacturerId")
                        .HasColumnType("integer");

                    b.Property<int?>("MedicineId")
                        .HasColumnType("integer");

                    b.Property<int?>("PackageId")
                        .HasColumnType("integer");

                    b.Property<int>("RegistrationNumber")
                        .HasColumnType("integer");

                    b.Property<int?>("StatementId")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("CheckId");

                    b.HasIndex("ManufacturerId");

                    b.HasIndex("MedicineId");

                    b.HasIndex("PackageId");

                    b.HasIndex("StatementId");

                    b.ToTable("Medication");
                });

            modelBuilder.Entity("PharmaceuticalWarehousing.Models.Medicine", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<int?>("CategoryId")
                        .HasColumnType("integer");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.HasIndex("CategoryId");

                    b.ToTable("Medicine");
                });

            modelBuilder.Entity("PharmaceuticalWarehousing.Models.Package", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<int?>("PackageTypeId")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("PackageTypeId");

                    b.ToTable("Package");
                });

            modelBuilder.Entity("PharmaceuticalWarehousing.Models.PackageType", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("Type")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.ToTable("PackageType");
                });

            modelBuilder.Entity("PharmaceuticalWarehousing.Models.Salesman", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("FirstName")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("LastName")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Patronymic")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.ToTable("Salesman");
                });

            modelBuilder.Entity("PharmaceuticalWarehousing.Models.Statement", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<int?>("WaybillId")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("WaybillId");

                    b.ToTable("Statement");
                });

            modelBuilder.Entity("PharmaceuticalWarehousing.Models.Waybill", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<int>("Number")
                        .HasColumnType("integer");

                    b.Property<int?>("ProviderId")
                        .HasColumnType("integer");

                    b.Property<DateTime>("ReceiptDate")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("Id");

                    b.HasIndex("ProviderId");

                    b.ToTable("Waybill");
                });

            modelBuilder.Entity("PharmaceuticalWarehousing.Models.Check", b =>
                {
                    b.HasOne("PharmaceuticalWarehousing.Models.Invoice", "Invoice")
                        .WithMany("Checks")
                        .HasForeignKey("InvoiceId");

                    b.Navigation("Invoice");
                });

            modelBuilder.Entity("PharmaceuticalWarehousing.Models.Invoice", b =>
                {
                    b.HasOne("PharmaceuticalWarehousing.Models.Counterparty", "Buyer")
                        .WithMany("Invoices")
                        .HasForeignKey("BuyerId");

                    b.HasOne("PharmaceuticalWarehousing.Models.Salesman", "Salesman")
                        .WithMany("Invoices")
                        .HasForeignKey("SalesmanId");

                    b.Navigation("Buyer");

                    b.Navigation("Salesman");
                });

            modelBuilder.Entity("PharmaceuticalWarehousing.Models.Medication", b =>
                {
                    b.HasOne("PharmaceuticalWarehousing.Models.Check", "Check")
                        .WithMany("Medications")
                        .HasForeignKey("CheckId");

                    b.HasOne("PharmaceuticalWarehousing.Models.Manufacturer", "Manufacturer")
                        .WithMany("Medications")
                        .HasForeignKey("ManufacturerId");

                    b.HasOne("PharmaceuticalWarehousing.Models.Medicine", "Medicine")
                        .WithMany("Medications")
                        .HasForeignKey("MedicineId");

                    b.HasOne("PharmaceuticalWarehousing.Models.Package", "Package")
                        .WithMany("Medications")
                        .HasForeignKey("PackageId");

                    b.HasOne("PharmaceuticalWarehousing.Models.Statement", "Statement")
                        .WithMany("Medications")
                        .HasForeignKey("StatementId");

                    b.Navigation("Check");

                    b.Navigation("Manufacturer");

                    b.Navigation("Medicine");

                    b.Navigation("Package");

                    b.Navigation("Statement");
                });

            modelBuilder.Entity("PharmaceuticalWarehousing.Models.Medicine", b =>
                {
                    b.HasOne("PharmaceuticalWarehousing.Models.Category", "Category")
                        .WithMany("Categories")
                        .HasForeignKey("CategoryId");

                    b.Navigation("Category");
                });

            modelBuilder.Entity("PharmaceuticalWarehousing.Models.Package", b =>
                {
                    b.HasOne("PharmaceuticalWarehousing.Models.PackageType", "PackageType")
                        .WithMany("Packages")
                        .HasForeignKey("PackageTypeId");

                    b.Navigation("PackageType");
                });

            modelBuilder.Entity("PharmaceuticalWarehousing.Models.Statement", b =>
                {
                    b.HasOne("PharmaceuticalWarehousing.Models.Waybill", "Waybill")
                        .WithMany("Statements")
                        .HasForeignKey("WaybillId");

                    b.Navigation("Waybill");
                });

            modelBuilder.Entity("PharmaceuticalWarehousing.Models.Waybill", b =>
                {
                    b.HasOne("PharmaceuticalWarehousing.Models.Counterparty", "Provider")
                        .WithMany("Waybills")
                        .HasForeignKey("ProviderId");

                    b.Navigation("Provider");
                });

            modelBuilder.Entity("PharmaceuticalWarehousing.Models.Category", b =>
                {
                    b.Navigation("Categories");
                });

            modelBuilder.Entity("PharmaceuticalWarehousing.Models.Check", b =>
                {
                    b.Navigation("Medications");
                });

            modelBuilder.Entity("PharmaceuticalWarehousing.Models.Counterparty", b =>
                {
                    b.Navigation("Invoices");

                    b.Navigation("Waybills");
                });

            modelBuilder.Entity("PharmaceuticalWarehousing.Models.Invoice", b =>
                {
                    b.Navigation("Checks");
                });

            modelBuilder.Entity("PharmaceuticalWarehousing.Models.Manufacturer", b =>
                {
                    b.Navigation("Medications");
                });

            modelBuilder.Entity("PharmaceuticalWarehousing.Models.Medicine", b =>
                {
                    b.Navigation("Medications");
                });

            modelBuilder.Entity("PharmaceuticalWarehousing.Models.Package", b =>
                {
                    b.Navigation("Medications");
                });

            modelBuilder.Entity("PharmaceuticalWarehousing.Models.PackageType", b =>
                {
                    b.Navigation("Packages");
                });

            modelBuilder.Entity("PharmaceuticalWarehousing.Models.Salesman", b =>
                {
                    b.Navigation("Invoices");
                });

            modelBuilder.Entity("PharmaceuticalWarehousing.Models.Statement", b =>
                {
                    b.Navigation("Medications");
                });

            modelBuilder.Entity("PharmaceuticalWarehousing.Models.Waybill", b =>
                {
                    b.Navigation("Statements");
                });
#pragma warning restore 612, 618
        }
    }
}
